# fly.toml app configuration file generated for my-portfolio-backend on 2024-07-31T12:24:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-portfolio-backend'
primary_region = 'jnb'

[build]

[[mounts]]
  source = 'my_portfolio_backend'
  destination = '/app/uploads'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
